// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type PaymentResponse struct {
	OrderID     string `json:"orderId"`
	BookID      string `json:"bookId"`
	CustomerID  string `json:"customerId"`
	Token       string `json:"token"`
	RedirectURL string `json:"redirect_url"`
}

type Query struct {
}
