type Query {
  borrowings: [Loan!]!
  topBorrowedBooks: [TopBorrowedBook!]!
}

type Mutation {
  borrowBook(memberId: Int!, bookId: Int!, tanggal_peminjaman: String!): Loan!
  returnBook(loanId: Int!): Loan!
  bayarDenda(paymentId: ID!): PaymentResponse!
}

type Loan {
  id: ID!
  member_id: Int!
  book_id: Int!
  tanggal_peminjaman: String
  tanggal_jatuh_tempo: String
  tanggal_pengembalian: String
  status: String
  denda: Int
  payment_info: PaymentResponse
}

type PaymentInfo {
  payment_id: Int!
  payment_status: String!
  payment_url: String!
}

type PaymentResponse {
  orderId: String!
  bookId: String!
  customerId: String!
  token: String!
  redirect_url: String!
}

type TopBorrowedBook {
  book_id: Int!
  total_peminjaman: Int!
}